config/routes.rb
Rails.application.routes.draw do

  
  root 'home#home'
  
  get '' => 'home#home'
  get 'contact' => 'home#contact'
  get 'modules' => 'options#index'
  get 'request_contact' => 'home#request_contact'

  resources :options

end

app/models/option.rb
class Option < ActiveRecord::Base
    validates_presence_of :title, :content, :professor, :credits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home #defining home page
  end

  def contact #adding contact page
  end
  
  def request_contact #fields for sending an email
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    
    if email.blank?
    flash[:alert] = I18n.t('home.request_contact.no_email') #make sure that an empty email isn't sent 
    else
    ContactMailer.contact_email(email, name, telephone, message).deliver_now #send email
    flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    
    redirect_to root_path
  end

end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params) #create a new option

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' } #display message if user clicks save
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new } #don't save otherwise
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' } #if option is 'updated' - save the changes
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit } #otherwise don't update
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url, notice: 'Option was successfully destroyed.' } #if user clicks 'delete', delete option
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:title, :content, :professor, :credits)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/home/contact.html.haml
%ul 
    %li
        %a{:href => "https://cs00932-com2025-project-casselwood.c9users.io"} Home
    %li
        %a{:href => "https://cs00932-com2025-project-casselwood.c9users.io/contact"} Contact Us
    %li
        %a{:href => "https://cs00932-com2025-project-casselwood.c9users.io/modules"} Module Selection
    
%h1= t('.title')
%p= t('.contact_us') 

//form for sending a message
= form_tag request_contact_path, method: 'post' do 
    = label_tag :name, t('.name')
    = text_field_tag :name, '', title: t('.enter_name'), size: 50
   
    = label_tag :email, t('.email')
    = email_field_tag :email, '', title: t('.enter_email')

    = label_tag :telephone, t('.telephone')
    = telephone_field_tag :telephone, '', title: t('.enter_telephone')

    = label_tag :message, t('.message')
    = text_field_tag :message, '', title: t('.enter_message'), size: 100
    
    = submit_tag t('.submit') 

app/views/home/home.html.haml
%ul 
    %li 
        %a{:href => "https://cs00932-com2025-project-casselwood.c9users.io"} Home
    %li 
        %a{:href => "https://cs00932-com2025-project-casselwood.c9users.io/contact"} Contact Us
    %li 
        %a{:href => "https://cs00932-com2025-project-casselwood.c9users.io/modules"} Module Selection
    
//creating a title 
%h1= t('.title') 
%p= t('.welcome')

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}

    %title= t('app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags

  %body
  
    - flash.each do |key, value|
      = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?
   
    = render 'shared/header'

    = yield
    
    = render 'shared/footer'

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %> <!-- if there are any errors then display error message -->
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2> <!-- don't allow module with errors to be saved -->

      <ul>
      <% @option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"> <!-- creating a form to allow user to create new module option -->
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :professor %><br>
    <%= f.text_field :professor %>
  </div>
  <div class="field">
    <%= f.label :credits %><br>
    <%= f.text_area :credits %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<div class="navigation"> <!-- creating navigation -->
        <ul>
             <li><a href="https://cs00932-com2025-project-casselwood.c9users.io">Home</a></li>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io/contact">Contact Us</a></li>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io/modules">Module Selection</a></li>
        </ul>
    </div>

<h1>Editing Option</h1>

<%= render 'form' %> <!-- display form to edit module option -->

<%= link_to 'Show', @option %> | <!-- link 'show' to the option -->
<%= link_to 'Back', options_path %> <!-- link 'back' to the options page -->

app/views/options/index.html.erb
<div class="navigation"> <!-- creating navigation -->
        <ul>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io">Home</a></li>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io/contact">Contact Us</a></li>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io/modules">Module Selection</a></li>
        </ul>
    </div>

<p id="notice"><%= notice %></p>

<h2>Listing Options</h2>

<table> <!-- creating a table to display the module information -->
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Professor</th>
      <th>Credits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody> <!-- .each method rolls through options to display information for each field, attempt to hide fields using jquery commands -->
    <% @options.each do |option| %>
      <tr>
        <td><%= option.title %><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %></td>
        <td><%= option.content %><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %></td>
        <td><%= option.professor %><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %></td>
        <td><%= option.credits %><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %></td>
        <td><%= link_to 'Show', option %><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %> <!-- link 'new option' to create a new option page -->

app/views/options/new.html.erb
<div class="navigation"> <!-- creating navigation -->
        <ul>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io">Home</a></li>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io/contact">Contact Us</a></li>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io/modules">Module Selection</a></li>
        </ul>
    </div>

<h1>New Option</h1> <!-- creating header -->

<%= render 'form' %> <!-- input form -->

<%= link_to 'Back', options_path %> <!-- link 'back' to the options page -->

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<div class="navigation"> <!-- creating navigation -->
        <ul>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io">Home</a></li>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io/contact">Contact Us</a></li>
            <li><a href="https://cs00932-com2025-project-casselwood.c9users.io/modules">Module Selection</a></li>
        </ul>
    </div>

<p> <!-- creating areas to display module info -->
  <strong>Title:</strong>
  <%= @option.title %> <!-- call different information from database -->
</p>

<p>
  <strong>Content:</strong>
  <%= @option.content %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @option.professor %>
</p>

<p>
  <strong>Credits:</strong>
  <%= @option.credits %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> | <!-- link 'edit' to the edit page-->
<%= link_to 'Back', options_path %> <!-- link 'back' to the module page-->

app/views/shared/_footer.html.haml
%footer
    %p! ="&copy; Module Selector CS00932 #{Time.now.year}"

app/views/shared/_header.html.haml
%header
    %h4 Welcome to my Module Selector Coursework COM2025!